services:
  builder:
    build: .
    volumes:
      - .:/Homeworks
      - apt_cache:/var/cache/apt
      - rc_objs:/Homeworks/RC/objs
      - pt_objs:/Homeworks/PathTracing/objs
    working_dir: /Homeworks

volumes:
  apt_cache:
  rc_objs:
  pt_objs: